config/routes.rb
Rails.application.routes.draw do
  
  
  get 'sessions/new'

  resources :users
  get 'users/new'

  get 'site/index'
  resources :sites
  get 'site/login'

  get 'site/signup'

  get 'site/contact'

  get 'site/about'

  get 'site/index'

  get 'site/login'
  
  get 'site/signup'

  get 'site/contact'

  get 'site/about'

  get 'posts/new'
  resources :posts do
    resources :comments
  end

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

resources :users ,path_names: { new: "signup" }
resources :sessions

  root 'site#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
      has_many :comments, dependent: :destroy
      
      validates :title, presence: true,
                    length: { minimum: 5 }

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  #validates_presence_of :email
  #validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commentor, :body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
 
def index
    @posts = Post.all
  end
  def show
    @post = Post.find(params[:id])
  end
def new 
     @post = Post.new
end 

def edit
  @post = Post.find(params[:id])
end

def create
  @post = Post.new(post_params)
 
  if @post.save
    redirect_to @post
else 
    render 'new'
end
end

def update
  @post = Post.find(params[:id])
 
  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
end
def destroy
  @post = Post.find(params[:id])
  @post.destroy
 
  redirect_to posts_path
end

private
  def post_params
    params.require(:post).permit(:title, :text)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

def create
      user = User.authenticate(params[:email],params[:password])
      if user
        session[:user_id] = user.id
        redirect_to root_url, :notice => "Logged in!"
      else
        flash.now.alert = "Invalid email or password"
      end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

  def login
  end

  def signup
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new
end

def create
    @user = User.new(user_params) ## Invoke user_params method
    if @user.save
      redirect_to root_url, notice: 'User was successfully created.' 
    else
      render action: 'new'
    end       
end
private
  ## Strong Parameters 
  def user_params
    params.require(:user).permit(:name, :password_digest, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commentor %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commentor %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>CodePros | Home</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <!-- Theme style -->
        <%= stylesheet_link_tag "_all-skins.min" %>
        <%= stylesheet_link_tag "AdminLTE.min" %>
  <!-- Ionicons -->
        <%= stylesheet_link_tag "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" %>
  <!-- Bootstrap 3.3.5 -->
         <%= stylesheet_link_tag "bootstrap.min" %>
  <!-- Font Awesome -->
          <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" %>
  
  <!-- jvectormap -->
          <%= stylesheet_link_tag "jquery-jvectormap-1.2.2" %>
          
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js" %>
  <%= javascript_include_tag "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"%>
  <![endif]-->
</head>

<body class="hold-transition skin-green layout-top-nav">
<div class="wrapper">

  <header class="main-header">
    <nav class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a href="#" class="navbar-brand"><b><%= image_tag("/img/logo.png", :alt => "CODE PROS") %></b></a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <i class="fa fa-bars"></i>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
            <li><a href="contest.aspx"><i class="fa fa-user" ></i> <span class="h4">Developers</span></a></li>
            <li><a href="#"><i class="fa fa-briefcase"></i> <span class="h4">Companies</span></a></li>
            <li><a href="#"><i class="fa fa-graduation-cap"></i> <span class="h4">Institutes</span></a></li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
        <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

            <li>
              <a href="#">
                <span class="hidden-xs">Welcome, Guest!</span>
            </a>
            </li>

            <li>
            <a href="signup.aspx">
           
                <i class="fa fa-edit"></i>
                <span class="hidden-xs">Sign Up</span>
            </a>
            </li>

            <li>
            <a href="login.aspx">
              
                <i class="fa fa-sign-in"></i>
                <span class="hidden-xs">Login</span>
            </a>
            </li>
        </ul>
      </div>
        <!-- /.navbar-custom-menu -->
      </div>
      <!-- /.container-fluid -->
    </nav>
  </header>
  <!-- Full Width Column -->
  <div class="content-wrapper">
    <div class="container">
<%= yield %>

</div>
    <!-- /.container -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="container">
      <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
      </div>
      <strong>Copyright &copy; 2015-2016 <a href="http://cbainc.in">CBA INC</a>.</strong> All rights
      reserved.
    </div>
    <!-- /.container -->
  </footer>
</div>
<!-- ./wrapper -->

<!-- jQuery 2.1.4 -->

<%= javascript_include_tag "jQuery-2.1.4.min.js" %>
<!-- Bootstrap 3.3.5 -->
<%= javascript_include_tag "bootstrap.min.js" %>
<!-- FastClick -->
<%= javascript_include_tag "fastclick.js" %>
<!-- AdminLTE App -->
<%= javascript_include_tag "app.min.js" %>
<!-- Sparkline -->
<%= javascript_include_tag "jquery.sparkline.min.js" %>
<!-- jvectormap -->
<%= javascript_include_tag "jquery-jvectormap-1.2.2.min.js" %>
<%= javascript_include_tag "jquery-jvectormap-world-mill-en.js" %>
<!-- SlimScroll 1.3.0 -->
<%= javascript_include_tag "jquery.slimscroll.min.js" %>
<!-- ChartJS 1.0.1 -->
<%= javascript_include_tag "Chart.min.js" %>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<%= javascript_include_tag "dashboard2.js" %>
<!-- AdminLTE for demo purposes -->
<%= javascript_include_tag "demo.js" %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing articles</h1>
 <%= link_to 'New post', new_post_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
       <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Posts</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>
 
<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/site/about.html.erb
  
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <ol class="breadcrumb">
          <li><a href="default.aspx"><i class="fa fa-home"></i> Home</a></li>
          <li class="active">Contact</li>
        </ol>
      </section>
    <div class="login-box">
  <div class="login-logo">
    <a href="default.aspx"><b>CODE</b>PROS</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Feel Free to Contact Us</p>

    <form>
      <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-7 col-xs-offset-1">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div>
    <!-- /.social-auth-links -->

    <a href="forgot.aspx">I forgot my password</a><br>
    <a href="signup.aspx" class="text-center">Get a free account</a>

  </div>
  <!-- /.login-box-body -->
        </div>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>

app/views/site/index.html.erb
 <div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>  

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>